### ISSUE TITLE
Caching issues with dynamic_page_cache while using module in combination with paragraphs

### ISSUE THREAD

**Issue by steffenr** [drunomics/amazon-product-widget#8]
While using the module in combination with the dynamic_page_cache module, i'll get the same products on every paragraph. 

The module is used in a paragraph and different ASINS are provided for the contents. 
The API Calls work fine and i get all product data in table *amazon_product_widget_key_value*. 

But I only get one entry in the *cache_dynamic_page_cache* table with tags *paragraph:169430 rendered* while opening the node pages. These are the cache tags of the first opened node containing an amazon product widget. 
The CacheId has the ID *response:[request_format]=html:[route]=amazon_product_widget.product_api35786c7117b4e38d0f169239752ce71158266ae2f6e4aa230fbbb87bd699c0e3*
Normally, I would expect one entry per paragraph.
Looks like drupal needs some more caching metadata for creating a unique identifier per paragraph for the amazon_product_widget.product_api route.

**Comment by mbm80** [comment]
yes, we found out the same when using the module on a site with dynamic page cache.
Fixed in 1.2.3/latest, closed PR (obsolete).
thanks though!
